baseURL: https://howarddo2208.github.io
languageCode: en-us
title: Howard Do
theme: "PaperMod"

params:
  meta:
    favicon: true
  comments: true
  homeInfoParams:
    Title: Sup bruh 😎 Welcome to my blog
    Content: I'm Howard, a developer based in HCMC, Vietnam. I'm an avid Linux user, use Arch btw. Love open-source and tinkering with terminal apps. I love my Neovim more than girlfriend, which I don't have. Check out my [dotfiles](https://github.com/howarddo2208/nixfiles). My knowledge is collected from various source from the internet, I'm trying to write blogs to help consolidate my thoughts and also wanting to help you guys a thing or two. If you find my blog helpful, follow my Twitter!

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/howarddo2208"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://twitter.com/howarddo2208"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    - name: "rss"
      url: "https://howarddo2208.github.io/index.xml"
  ShowReadingTime: true
  author: "Howard Do"
  contact: "howarddo2208@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

  #Google Analytics 4 optional
  # env: #production
  # GoogleAnalytics: "G-00000XXXXX"
  # sitemap:
  #   changefreq: daily
  #   filename: sitemap.xml
  #   priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20

enableGitInfo: true
frontmatter:
  lastmod: ["lastmod", ":git", "date", "publishDate"]
